### ISSUE TITLE
[Meta] Widget/Setup Ideas

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.fuse#249]
### Skin section

Home Widgets

### Feature description

This isn’t a skin request, but more looking to find ideas on how to improve the discovery of Movies and TV shows on Kodi. I’ve been using Kodi for well over a decade now, and have tried skin after skin, and one thing that has always plagued my setup is discovery of new titles to watch. If I know exactly what I wanted to watch, Kodi is fantastic, but if I didn’t… well Kodi isn’t great at surfacing new content. Apologies if this isn’t allowed, feel free to delete it if not!

I think with the advancements you have made in Arctic Fuse, TMDb Helper, and some other addons like Autowidget, I think this can be vastly improved to close to official streaming service levels. I think it won’t ever be at that level without some kind of service that tracks user statistics and curates lists for widgets like they use, but I think we can get close.

So I was hoping you, jurialmunkey (and others, please!), if you were comfortable doing it - share what you have setup! How have you improved discoverability? What kind of widgets do you use? How do you take advantage of TMDb Helper’s Discover feature? How do you use nodes? Any cool ideas that can help surface great content that doesn’t always feel static to the Home Screen, all ideas welcome!

### Why is this feature needed? Please justify and explain.

-

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.
